package reports

import (
	"fmt"

	"github.com/johnfercher/maroto/pkg/color"
	"github.com/johnfercher/maroto/pkg/consts"
	"github.com/johnfercher/maroto/pkg/pdf"
	"github.com/johnfercher/maroto/pkg/props"
)

type PDFGenerator struct{}

func (g *PDFGenerator) Generate(filePath string, data ReportData) error {
	m := pdf.NewMaroto(consts.Portrait, consts.A4)
	m.SetPageMargins(20, 10, 20)

	// Colors
	darkBlue := color.Color{Red: 0, Green: 95, Blue: 115}
	lightBlue := color.Color{Red: 233, Green: 236, Blue: 239}

	// Header
	m.RegisterHeader(func() {
		m.Row(20, func() {
			m.Col(12, func() {
				m.Text("GOSINT Report", props.Text{
					Top:   3,
					Size:  16,
					Style: consts.Bold,
					Align: consts.Center,
					Color: darkBlue,
				})
			})
		})
	})

	// Footer
	m.RegisterFooter(func() {
		m.Row(10, func() {
			m.Col(12, func() {
				m.Text("Generated by GOSINT Toolkit", props.Text{
					Size:  8,
					Align: consts.Center,
					Color: color.Color{Red: 100, Green: 100, Blue: 100},
				})
			})
		})
	})

	// Body
	m.Row(10, func() {
		m.Col(12, func() {
			m.Text(fmt.Sprintf("Target: %s", data.Target), props.Text{
				Top:   3,
				Size:  12,
				Style: consts.Bold,
			})
		})
	})
	m.Row(10, func() {
		m.Col(12, func() {
			m.Text(fmt.Sprintf("Date: %s", data.ScanDate.Format("2006-01-02 15:04:05")), props.Text{
				Top:  3,
				Size: 10,
			})
		})
	})
	m.Row(10, func() {
		m.Col(12, func() {
			m.Text(fmt.Sprintf("Mode: %s | Duration: %s", data.ScanMode, data.Duration), props.Text{
				Top:  3,
				Size: 10,
			})
		})
	})

	m.Line(1.0)

	// Technologies
	if len(data.Technologies) > 0 {
		m.Row(10, func() {
			m.Col(12, func() {
				m.Text("Technologies", props.Text{
					Top:   3,
					Size:  12,
					Style: consts.Bold,
					Color: darkBlue,
				})
			})
		})

		header := []string{"Category", "Name", "Version"}
		contents := [][]string{}

		for _, t := range data.Technologies {
			contents = append(contents, []string{
				t.Category,
				t.Name,
				t.Version,
			})
		}

		m.TableList(header, contents, props.TableList{
			HeaderProp: props.TableListContent{
				Size:      9,
				GridSizes: []uint{3, 6, 3},
			},
			ContentProp: props.TableListContent{
				Size:      9,
				GridSizes: []uint{3, 6, 3},
			},
			Align:              consts.Left,
			HeaderContentSpace: 1,
			Line:               true,
		})
	}

	// Subdomains
	if len(data.Subdomains) > 0 {
		m.Row(12, func() {
			m.Col(12, func() {
				m.Text(fmt.Sprintf("Subdomains (%d)", len(data.Subdomains)), props.Text{
					Top:   5,
					Size:  12,
					Style: consts.Bold,
					Color: darkBlue,
				})
			})
		})

		header := []string{"Subdomain", "IP", "Status"}
		contents := [][]string{}

		// Limit PDF rows to avoid huge files if thousands
		limit := 200
		count := 0
		for _, s := range data.Subdomains {
			if count >= limit {
				break
			}
			contents = append(contents, []string{
				s.Subdomain,
				s.IP,
				s.Status,
			})
			count++
		}

		m.TableList(header, contents, props.TableList{
			HeaderProp: props.TableListContent{
				Size:      9,
				GridSizes: []uint{6, 4, 2},
			},
			ContentProp: props.TableListContent{
				Size:      9,
				GridSizes: []uint{6, 4, 2},
			},
			AlternatedBackground: &lightBlue,
			Align:                consts.Left,
		})

		if len(data.Subdomains) > limit {
			m.Row(10, func() {
				m.Col(12, func() {
					m.Text(fmt.Sprintf("... and %d more (truncated)", len(data.Subdomains)-limit), props.Text{
						Style: consts.Italic,
						Size:  8,
					})
				})
			})
		}
	}

	return m.OutputFileAndClose(filePath)
}
